In [1]:
import torch
import numpy as np

Тензоры 
1. Инициализация

In [2]:
data = [[1, 2],
        [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

Из  массива numpy

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

Из другого тензора

In [5]:
x_ones = torch.ones_like(x_data) # сохраняет свойства x_data
print(f"Единичный Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # переопределяет тип данных x_data
print(f"Случайный Tensor: \n {x_rand} \n")

Единичный Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Случайный Tensor: 
 tensor([[0.5798, 0.9967],
        [0.2137, 0.7122]]) 



In [8]:
shape = (2,3,4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Случайный Tensor: \n {rand_tensor} \n")
print(f"Единичный Tensor: \n {ones_tensor} \n")
print(f"Нулевой Tensor: \n {zeros_tensor}")

Случайный Tensor: 
 tensor([[[0.1380, 0.8281, 0.3926, 0.8615],
         [0.6397, 0.1259, 0.0022, 0.2879],
         [0.8608, 0.0960, 0.0699, 0.1218]],

        [[0.4063, 0.0111, 0.3135, 0.9057],
         [0.3825, 0.5822, 0.3966, 0.7973],
         [0.4635, 0.0522, 0.0383, 0.9613]]]) 

Единичный Tensor: 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 

Нулевой Tensor: 
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


2.Операции над тензорами

In [10]:
tensor = torch.rand(3,4)

print(f"Размерность : {tensor.shape}")
print(f"Тип данных : {tensor.dtype}")
print(f"Устройство хранения: {tensor.device}")

Размерность : torch.Size([3, 4])
Тип данных : torch.float32
Устройство хранения: cpu


In [11]:
#Перенос тензора на GPU
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f"Устройство хранения: {tensor.device}")

Устройство хранения: cuda:0


Индексирование в стиле numpy

In [12]:
tensor = torch.ones(4, 4)
print('Элемент тензора в позиции (1, 2)', tensor[1,2])
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

Элемент тензора в позиции (1, 2) tensor(1.)
First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Присоединение тензоров

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [14]:
t1.shape

torch.Size([4, 12])

Арифметические операции

In [15]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [16]:
# Поэлементное умножение. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Тензор из одного элемента

In [17]:
agg = tensor.sum()
agg_item = agg.item() #print value to the stream
print(agg, type(agg_item))
print(agg_item, type(agg_item))

tensor(12.) <class 'float'>
12.0 <class 'float'>


Операции, изменяют сам тензор 

In [18]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Мост к NumPy. 
Tensor to Numpy

In [19]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Changes in the NumPy array reflects in the tensor.

In [20]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor

In [22]:
n = np.ones(5)
t = torch.from_numpy(n)
n,t

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

Changes in the NumPy array reflects in the tensor.

In [23]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


MAX

In [24]:
a = torch.randn(3, 4)
a

tensor([[ 0.9733, -1.3926,  0.7721, -0.2278],
        [-0.2548,  0.8176, -0.5493,  0.4456],
        [-0.1063, -0.9682, -0.5427, -0.7665]])

In [25]:
torch.max(a,dim=1)

torch.return_types.max(
values=tensor([ 0.9733,  0.8176, -0.1063]),
indices=tensor([0, 1, 0]))

In [26]:
torch.max(a,dim=0)

torch.return_types.max(
values=tensor([0.9733, 0.8176, 0.7721, 0.4456]),
indices=tensor([0, 1, 0, 1]))

In [27]:
torch.max(a)

tensor(0.9733)