In [3]:
import numpy as np

In [4]:
array1 = [[1,2],[3,4]]
array2 = [[5,6],[8,9]]

In [5]:
array1 = np.array(array1)
array2 = np.array(array2)

type(array1)

numpy.ndarray

In [6]:
array1 + array2

array([[ 6,  8],
       [11, 13]])

In [7]:
array1 * array2

array([[ 5, 12],
       [24, 36]])

In [8]:
array1 @ array2

array([[21, 24],
       [47, 54]])

In [9]:
array1.shape

(2, 2)

In [10]:
array1.reshape((4,))

array([1, 2, 3, 4])

In [11]:
np.reshape(array1, (4,))

array([1, 2, 3, 4])

In [18]:
a = np.random.randint(low=0, high=100, size=(2,3,4))

In [14]:
np.mean(array1)

2.5

In [19]:
np.mean(a, axis=0)

array([[55. , 56.5, 25.5, 48. ],
       [74. , 87. , 70.5, 55.5],
       [58.5, 26. , 51. , 54. ]])