In [1]:

import numpy as np

In [5]:
array1 = [[1,2],
         [3,4]]

array2 = [[5,6],
          [8,9]]

In [9]:
array1 = np.array(array1)
array2 = np.array(array2)

type(array1)

numpy.ndarray

In [10]:
array1 * array2

array([[ 5, 12],
       [24, 36]])

In [11]:
array1.shape

(2, 2)

In [12]:
array1.reshape((4,))

array([1, 2, 3, 4])

In [13]:
np.reshape(array1, (4,))

array([1, 2, 3, 4])

In [15]:
np.random.randint(low=0, high=100, size=(2,3,4))

array([[[12, 42, 89, 93],
        [20, 96, 46, 47],
        [81, 89, 55, 41]],

       [[32, 42, 58, 53],
        [97,  0, 49, 96],
        [96, 75, 24, 67]]])

In [16]:
np.mean(array1)

2.5

In [17]:
np.mean(array1, axis=1)

array([1.5, 3.5])

In [18]:
np.mean(a, axis=0)

NameError: name 'a' is not defined