In [3]:
import numpy as np

In [5]:
array1 = [[1,2],
         [3,4]]
array2 = [[5,6],
         [8,9]]
type(array1)

list

In [6]:
array1 = np.array(array1)
array2 = np.array(array2)

type(array1)

numpy.ndarray

In [7]:
array1 + array2

array([[ 6,  8],
       [11, 13]])

In [8]:
array1 * array2

array([[ 5, 12],
       [24, 36]])

In [9]:
array1 @ array2

array([[21, 24],
       [47, 54]])

In [10]:
array1.shape

(2, 2)

In [11]:
array1.reshape((4,))

array([1, 2, 3, 4])

In [12]:
np.reshape(array1, (4,))

array([1, 2, 3, 4])

In [13]:
np.random.randint(low=0, high=100, size=(2,3,4))

array([[[81, 30, 68, 60],
        [30, 89, 78, 39],
        [ 9, 94,  7, 89]],

       [[ 8, 48, 84, 49],
        [51, 13, 78,  4],
        [30, 23, 69, 73]]])

In [14]:
np.mean(array1)

2.5

In [16]:
np.mean(array1, axis=0)

array([2., 3.])

In [17]:
np.mean(a, axis=0)

NameError: name 'a' is not defined