In [3]:
import numpy as np

In [1]:
array1 = [[1,2],[3,4]]

array2 = [[5,6],[7,8]]
type(array1)

list

In [5]:
array1 = np.array(array1)
array2 = np.array(array2)

type(array1)

numpy.ndarray

In [6]:
array1 + array2

array([[ 6,  8],
       [10, 12]])

In [7]:
array1 @ array2

array([[19, 22],
       [43, 50]])

In [8]:
array1.shape

(2, 2)

In [9]:
array1.reshape((4,))

array([1, 2, 3, 4])

In [10]:
np.reshape(array1,(4,))

array([1, 2, 3, 4])

In [15]:
a = np.random.randint(low=0, high=100, size=(2,3,4))

In [12]:
np.mean(array1)

2.5

In [16]:
np.mean(a, axis=0)

array([[52.5, 89. , 38. , 76. ],
       [71. , 75.5, 48. , 69.5],
       [31. , 39. , 40. , 29.5]])