In [1]:
import numpy as np

In [5]:
array1 = [[1, 2], 
         [3, 4]]
array2 = [[5, 6], 
         [8, 9]]
type(array1)

list

In [6]:
array1 = np.array(array1)
array2 = np.array(array2)
type(array1)

numpy.ndarray

In [7]:
array1 + array2

array([[ 6,  8],
       [11, 13]])

In [10]:
array1 * array2

array([[ 5, 12],
       [24, 36]])

In [13]:
array1 @ array2

array([[21, 24],
       [47, 54]])

In [16]:
array1.shape

(2, 2)

In [20]:
array1.reshape((4,))

array([1, 2, 3, 4])

In [22]:
np.random.randint(low=0, high=100, size=(2, 3, 4))

array([[[50, 55,  5, 69],
        [90, 24, 80, 50],
        [31, 69, 17, 57]],

       [[65,  0, 19, 78],
        [25, 97, 33,  3],
        [44, 77, 88, 71]]])

In [23]:
np.mean(array1)

2.5

In [24]:
np.mean(array1, axis=1)

array([1.5, 3.5])