In [2]:
import numpy as np

In [3]:
array1 = [[1,2], [3,4]]
array2 = [[5,6], [8,9]]

In [4]:
array1 = np.array(array1)
array2 = np.array(array2)

In [5]:
array1 + array2

array([[ 6,  8],
       [11, 13]])

In [6]:
array1 @ array2

array([[21, 24],
       [47, 54]])

In [7]:
array1 * array2

array([[ 5, 12],
       [24, 36]])

In [8]:
array1.shape


(2, 2)

In [9]:
array1.reshape ((4,))

array([1, 2, 3, 4])

In [10]:
np.reshape(array1, (4,))

array([1, 2, 3, 4])

In [14]:
a = np.random.randint(low=0, high=100, size=(2,3,4))

In [13]:
np.mean(array1, axis=0)

array([2., 3.])

In [15]:
np.mean(a, axis=0)

array([[44.5, 43. , 45.5, 29. ],
       [21. , 68. , 44. , 30.5],
       [43. , 66.5, 54.5, 36. ]])