In [1]:
import numpy as np

In [2]:
array1 = [[1,2],
          [3,4]]
array2 = [[5,6],
          [8,9]]

In [5]:
array1 = np.array(array1)
array2 = np.array(array2)

#type(array1)

array1+array2

array([[ 6,  8],
       [11, 13]])

In [7]:
array1*array2

array([[ 5, 12],
       [24, 36]])

In [9]:
array1@array2

array([[21, 24],
       [47, 54]])

In [16]:
array1.reshape((4,))

array([1, 2, 3, 4])

In [23]:
a = np.random.randint(0,100,(2,3,4))

In [24]:
np.mean(a, 1)

array([[42.        , 43.33333333, 23.33333333, 61.        ],
       [41.66666667, 53.        , 70.66666667, 17.66666667]])