In [5]:
import numpy as np

In [9]:
array1 = [[1,2],
         [3,4]]

array2 = [[5,6],
         [8,9]]

type(array1)

list

In [10]:
array1 = np.array(array1)
array2 = np.array(array2)

type(array1)

numpy.ndarray

In [11]:
array1 + array2

array([[ 6,  8],
       [11, 13]])

In [12]:
array1 * array2

array([[ 5, 12],
       [24, 36]])

In [13]:
array1 @ array2

array([[21, 24],
       [47, 54]])

In [14]:
array1.shape

(2, 2)

In [15]:
array1.reshape((4,))

array([1, 2, 3, 4])

In [16]:
np.reshape(array1, (4,))

array([1, 2, 3, 4])

In [21]:
np.random.randint(low=0, high=100, size=(2,3,4))

array([[[48, 78, 24, 80],
        [48, 49, 14, 44],
        [51, 41,  7, 52]],

       [[48, 72, 65, 88],
        [73, 68, 16, 11],
        [63, 66, 37,  5]]])

In [22]:
np.mean(array1)

2.5

In [23]:
np.mean(array1, axis=0)

array([2., 3.])