In [1]:
import numpy as np

In [3]:
array1 = [[1,2],
         [3,4]]

array2 = [[5,6],
         [8, 9]]

type(array1)

list

In [4]:
array1 = np.array(array1)
array2 = np.array(array2)

type(array1)

numpy.ndarray

In [5]:
array1 + array2

array([[ 6,  8],
       [11, 13]])

In [6]:
array1 * array2

array([[ 5, 12],
       [24, 36]])

In [7]:
array1 @ array2

array([[21, 24],
       [47, 54]])

In [10]:
array1.shape

(2, 2)

In [11]:
array1.reshape((4,))

array([1, 2, 3, 4])

In [12]:
np.reshape(array1, (4,))

array([1, 2, 3, 4])

In [18]:
a = np.random.randint(low=0, high=100, size=(2,3,4))

In [14]:
np.mean(array1)

2.5

In [19]:
np.mean(a, axis=0)

array([[91. , 36. , 41.5, 14.5],
       [54.5, 21. , 36.5, 54.5],
       [34. , 47. , 43.5, 60.5]])