In [5]:
import numpy as np

In [6]:
array1 = [[1,2],[3,4]]
array2 = [[5,6],[7,8]]

type(array1)

list

In [7]:
array1 = np.array(array1)
array2 = np.array(array2)

type(array1)

numpy.ndarray

In [8]:
array1+array2

array([[ 6,  8],
       [10, 12]])

In [9]:
array1*array2

array([[ 5, 12],
       [21, 32]])

In [10]:
array1.shape

(2, 2)

In [12]:
array1.reshape((4,))

array([1, 2, 3, 4])

In [17]:
a=np.random.randint(low=0,high=100, size=(2,3,4))

In [14]:
np.mean(array1)

2.5

In [18]:
np.mean(a,axis=0)

array([[ 7.5, 55.5, 63.5, 69. ],
       [55.5, 12. , 59. , 52.5],
       [23. , 46. , 56.5, 69. ]])